IMAGE_CODE_EXPIRES_SECONDS = 120   # 图片验证码在redis中的有效期,单位:s

HOUSE_LIST_PAGE_CAPACITY = 3 # 房源列表页每页显示房屋数目

HOME_PAGE_MAX_HOUSES = 5

HOME_PAGE_DATA_REDIS_EXPIRE_SECOND = 86400  #首页图片redis有效期
REDIS_AREA_INFO_EXPIRES_SECONDES = 86400   #首页城区信息redis有效期
REDIS_HOUSE_INFO_EXPIRES_SECONDES = 86400  #房屋信息的redis缓存时间